make/autoconf/platform.m4
src/hotspot/os/linux/os_linux.cpp

The mainline OpenJDK has apply the patch which is only add support for RV64G:
[8199138: Add RISC-V support to Zero](https://hg.openjdk.java.net/jdk/jdk/rev/6d2586f260a0)
In addition, add RISC-V 32bit support to zero.

Add RISC-V support to Zero (both RV64G and RV32G)

---

make/autoconf/platform.m4
src/hotspot/os/linux/os_linux.cpp

It works with qemu user mode and passed both `java -version` and `startup.helloworld` case in SPECjvm2008.

Add RISC-V 32Bit support to Zero

---

src/hotspot/cpu/riscv32/abstractInterpreter_riscv32.cpp
src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp

Add the riscv32 dir into src/hotspot/cpu.
Add the abstractInterpreter_riscv32.cpp into cpu dir, it is same with the abstractInterpreter_riscv64.cpp of BishengJDK, except I changed the file name and use the riscv32 instead of the riscv64 in comments. The change is about the stack pointer 16-aligned.
Add the templateInterpreterGenerator_riscv32.cpp into cpu dir, it is same with the templateInterpreterGenerator_riscv64.cpp of BishengJDK, except I changed the file name and use the frame_riscv32.hpp intead of the frame_amd64.hpp in comments. The frame_amd64.hpp in the comments is a mistake from aarch64 backend, it is come from amd backend more earlier.

Add the riscv32 dir and files of interpreter

---

src/hotspot/cpu/riscv32/templateTable_riscv32.cpp
src/hotspot/cpu/riscv32/templateTable_riscv32.hpp

Add the templateTable_riscv32.hpp, it is same with the templateTable_riscv64.hpp of the BishengJDK, except changed the file name and some '64' text.
Add the templateTable_riscv32.cpp, it is same with the templateTable_riscv64.cpp of the BishengJDK, but changed the instructions of riscv64. The changed instructions: addw->add, addiw->addi, subw->sub, mulw->mul, andrw->andr, orrw->orr, xorrw->xorr, sllw->sll, sraw->sra, srlw->srl, negw->neg.
Add the iscas copyright into templateTable_riscv32.cpp.

Add templateTable files into src/hotspot/cpu/riscv32

---

src/hotspot/cpu/riscv32/globalDefinitions_riscv32.hpp
src/hotspot/cpu/riscv32/globals_riscv32.hpp

Add the globalDefinitions_riscv32.hpp, it is same with the globalDefinitions_riscv64.hpp of the BishengJDK, except changed the file name and some '64' text.
Add the globals_riscv32.hpp, it is same with the globals_riscv64.hpp of the BishengJDK, but changed the value of DEFAULT_STACK_SHADOW_PAGES. Since use LP32, we do not need too many shadow pages and set the same value as arm temporarily.
Add the iscas copyright into globals_riscv32.hpp.

Add global files into src/hotspot/cpu/riscv32

---

src/hotspot/cpu/riscv32/interpreterRT_riscv32.cpp
src/hotspot/cpu/riscv32/interpreterRT_riscv32.hpp

Add the interpreterRT_riscv32.hpp file, it is same with the interpreterRT_riscv64.hpp of BishengJDK, except change the text 64 to 32.
Add the interpreterRT_riscv32.cpp file, it changes some instructons from interpreterRT_riscv64.cpp of BishengJDK. The changed instructions:ld->flw, sd->fsw, lwu->lw.

Add the interpreterRT files into src/hotspot/cpu/riscv32

---

src/hotspot/cpu/riscv32/relocInfo_riscv32.cpp
src/hotspot/cpu/riscv32/relocInfo_riscv32.hpp

Add the relocInfo_riscv32.cpp and relocInfo_riscv32.hpp files, they are same with the files of the BishengJDK for riscv64, except changed the file name and some '64' text.

Add relocInfo files into src/hotspot/cpu/riscv32

---

src/hotspot/cpu/riscv32/codeBuffer_riscv32.hpp

Add the codeBuffer_riscv32.hpp file, it is same with the file of the BishengJDK for riscv64, except changed the file name and some '64' text.

Add codeBuffer_riscv32.hpp file into src/hotspot/cpu/riscv32

---

src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp
src/hotspot/cpu/riscv32/nativeInst_riscv32.hpp

Add the nativeInst_riscv32.hpp, compared with the nativeInst_riscv64.hpp of BishengJDK, it has changed: 1)changed the 64 in file name and define; 2)commented the check_li64_data_dependency(), is_li64_at(), class NativeMoveRegMem; 3)changed the 64 in 'enum RISCV64specific_constants' to 32.
Add the nativeInst_riscv32.cpp, compared with the nativeInst_riscv64.cpp of BishengJDK, it has changed the 64 in include filename and log, commented the si_li64_at().

Add nativeInst files for src/hotspot/cpu/riscv32

---

src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp
src/hotspot/cpu/riscv32/stubRoutines_riscv32.cpp
src/hotspot/cpu/riscv32/stubRoutines_riscv32.hpp
src/hotspot/cpu/riscv32/vtableStubs_riscv32.cpp

The stubGenerator_riscv32.cpp is same with the stubGenerator_riscv64.cpp of BishengJDK, but changed the 64 text and instructions: addw->add, addiw->addi, subw->sub, ld->flw, sd->fsw, lwu->lw.
The stubRoutines_riscv32.cpp is same with the stubRoutines_riscv64.cpp of BishengJDK, except changed the text '64' to '32'.
The stubRoutines_riscv32.hpp is same with the stubRoutines_riscv64.hpp of BishengJDK, except changed the text '64' to '32'.
The vtableStubs_riscv32.cpp is same with the vtableStubs_riscv64.cpp of BishengJDK, but changed the 64 text and instructions: lwu->lw, ld->flw.

Add stub files into src/hotspot/cpu/riscv32

---

src/hotspot/cpu/riscv32/disassembler_riscv32.hpp

Add the disassembler_riscv32.hpp, it is same with the disassembler_riscv64.hpp of BishengJDK, just changed the 64 text in the file name and define.

Add the disassembler_riscv32.hpp into src/hotspot/cpu/riscv32/

---

src/hotspot/cpu/riscv32/assembler_riscv32.cpp

Update generated code by riscv32-asmtest.py into assembler_riscv32.cpp and remove the generated code for riscv64.
Remove pseudoinstructions negw from assembler_riscv32.cpp.

update generated code by riscv32-asmtest.py into assembler_riscv32.cpp

---

src/hotspot/cpu/riscv32/gc/shared/barrierSetAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/gc/shared/barrierSetAssembler_riscv32.hpp

Add the barrierSetAssembler_riscv32.cpp file, it is same with the barrierSetAssembler_riscv64.cpp of the BishengJDK for riscv64, except changed some '64' text and instructions: lwu->lw, ld->lw, sd->sw.
Add the barrierSetAssembler_riscv32.hpp file, it is same with the barrierSetAssembler_riscv64.hpp of the BishengJDK for riscv64, except changed some '64' text.

Add barrierSetAssembler files into src/hotspot/cpu/riscv32

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp

The is_valid_riscv32_address() is useless in the rv32g model. Because the address of rv32g is always 32 bit.
The rv32g use the sv32 mode.

remove the is_valid_riscv32_address()

---

src/hotspot/cpu/riscv32/assembler_riscv32.cpp
src/hotspot/cpu/riscv32/assembler_riscv32.hpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

Remove the declaration of li32 in assembler_riscv32.hpp.
Remove the function of Assembler::li32 in assembler_riscv32.cpp.
Rename the function of li32 to li and remove operation of clear upper 32bit in macroAssembler_riscv32.cpp.

Fix li32 in assembler and macroAssembler moudle

---

src/hotspot/cpu/riscv32/assembler_riscv32.cpp

Rename int64_t to int32_t and add missing 'addi' after 'lui'

Fix Assembler:li32 in assembler_riscv32.cpp

---

src/hotspot/cpu/riscv32/gc/shared/cardTableBarrierSetAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/gc/shared/cardTableBarrierSetAssembler_riscv32.hpp
src/hotspot/cpu/riscv32/gc/shared/modRefBarrierSetAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/gc/shared/modRefBarrierSetAssembler_riscv32.hpp

Add the cardTableBarrierSetAssembler_riscv32.cpp, it is same with the cardTableBarrierSetAssembler_riscv64.cpp of BishengJDK, except changed the text '64' to '32'.
Add the cardTableBarrierSetAssembler_riscv32.hpp, it is same with the cardTableBarrierSetAssembler_riscv64.hpp of BishengJDK, except changed the text '64' to '32'.
Add the modRefBarrierSetAssembler_riscv32.cpp, it is same with the modRefBarrierSetAssembler_riscv64.cpp of BishengJDK, except changed the text '64' to '32'.
Add the modRefBarrierSetAssembler_riscv32.hpp, it is same with the modRefBarrierSetAssembler_riscv64.hpp of BishengJDK, except changed the text '64' to '32'.

Add remained files into src/hotspot/cpu/riscv32/gc/shared

---

src/hotspot/cpu/riscv32/gc/g1/g1BarrierSetAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/gc/g1/g1BarrierSetAssembler_riscv32.hpp
src/hotspot/cpu/riscv32/icBuffer_riscv32.cpp

Add the g1BarrierSetAssembler_riscv32.cpp, it is same with the g1BarrierSetAssembler_riscv64.cpp of BishengJDK, except changed the text '64' to '32' and some instructions: ld->lw, sd->sw, lwu->lw.
Add the g1BarrierSetAssembler_riscv32.hpp, it is same with the g1BarrierSetAssembler_riscv64.hpp of BishengJDK, except changed the text '64' to '32'.
Fix typo in icBuffer_riscv32.cpp

Add g1BarrierSetAssembler files into src/hotspot/cpu/riscv32/gc/g1

---

src/hotspot/cpu/riscv32/jniFastGetField_riscv32.cpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

Update the jniFastGetField_riscv32.cpp: lwu->lw.
Update the macroAssembler_riscv32.cpp: ld->lw, sd->sw, addw->add, addiw->addi, subw->sub, lwu->lw;
also update the 0x%016lx in debug32() to 0x%016x.

Fix the lwu error in jniFastGetField_riscv32.cpp

---

src/hotspot/cpu/riscv32/gc/shenandoah/c1/shenandoahBarrierSetC1_riscv32.cpp
src/hotspot/cpu/riscv32/gc/shenandoah/shenandoahBarrierSetAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/gc/shenandoah/shenandoahBarrierSetAssembler_riscv32.hpp
src/hotspot/cpu/riscv32/gc/shenandoah/shenandoah_riscv32.ad

Add the shenandoahBarrierSetC1_riscv32.hpp, it is same with the shenandoahBarrierSetC1_riscv64.hpp of BishengJDK, except changed the text '64' to '32'.
Add the shenandoahBarrierSetAssembler_riscv32.cpp, it is same with the shenandoahBarrierSetAssembler_riscv64.cpp of BishengJDK, except changed the text '64' to '32' and some instructions: ld->lw, sd->sw, lwu->lw.
Add the shenandoahBarrierSetAssembler_riscv32.hpp, it is same with the shenandoahBarrierSetAssembler_riscv64.hpp of BishengJDK, except changed the text '64' to '32'.
Add the shenandoah_riscv32.ad, it is same with the shenandoah_riscv64.hpp of BishengJDK, except changed the text '64' to '32'.

Add shenandoah moudle into src/hotspot/cpu/riscv32/gc/shenandoah

---

src/hotspot/cpu/riscv32/nativeInst_riscv32.hpp
src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp
src/hotspot/share/runtime/vm_version.cpp
src/hotspot/share/utilities/macros.hpp

Fix 'NativeMovRegMem has not been declared' errors.
Fix 'RISCV32_ONLY was not declared' error.
Fix 'sharedRuntime_riscv32.cpp:43:10: fatal error: vmreg_riscv64.inline.hpp: No such file or directory' error.

Rv32g dev shiningning fix native inst

---

src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp
src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp
src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp
src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

Fix typo of 'lw' in src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp.
Fix error in src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp.
Fix error: 'class InterpreterMacroAssembler' has no member named 'slliw' error in src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp
Fix error: 'class InterpreterMacroAssembler' has no member named 'xx' in src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp

Rv32g dev zdl fix no match function or member

---

src/jdk.hotspot.agent/linux/native/libsaproc/libproc.h

Add the elif defined(riscv32) into the /src/jdk.hotspot.agent/linux/native/libsaproc/libproc.h.
After this fix, the interpreter can compiled success.

 Fix the error of get_lwp_regs()

---

src/hotspot/os_cpu/linux_riscv32/atomic_linux_riscv32.hpp
src/hotspot/os_cpu/linux_riscv32/os_linux_riscv32.cpp
src/hotspot/os_cpu/linux_riscv32/os_linux_riscv32.hpp

Remove unused codes about atomic_load_long_bootstrap, atomic_store_long_bootstrap, atomic_load_long_func and atomic_store_long_func from os_linux_riscv32.cpp.
Remove unused codes about atomic_load_long_bootstrap, atomic_store_long_bootstrap, atomic_load_long_func and atomic_store_long_func from os_linux_riscv32.hpp.
Remove unused codes in atomic_linux_riscv32.hpp.

Fix unused template in atomic_linux_riscv32.hpp and os_linux_riscv32

---

src/jdk.hotspot.agent/linux/native/libsaproc/LinuxDebuggerLocal.c
src/jdk.hotspot.agent/linux/native/libsaproc/ps_proc.c
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/HotSpotAgent.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/MachineDescriptionRiscv32.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/linux/LinuxCDebugger.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/linux/riscv32/LinuxRISCV32CFrame.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/linux/riscv32/LinuxRISCV32ThreadContext.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/proc/ProcDebuggerLocal.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/proc/riscv32/ProcRISCV32Thread.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/proc/riscv32/ProcRISCV32ThreadContext.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/proc/riscv32/ProcRISCV32ThreadFactory.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/remote/riscv32/RemoteRISCV32Thread.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/remote/riscv32/RemoteRISCV32ThreadContext.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/remote/riscv32/RemoteRISCV32ThreadFactory.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/risv32/RISCV32ThreadContext.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/utilities/PlatformInfo.java

Add java classes for riscv32, and update the riscv32 config in some files. They are the same with the 64
version of BishengJDK, just change the text '64' to '32'.

Add the java classes for riscv32

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/riscv32.ad
src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp

The input param upper_bits still keep the 32 value, it must be 16 in rv32g. The 32 value is used in rv64g. So update it.
This patch can avoid the assert error in the clear_upper_bits() of macroAssembler_riscv32.hpp.

Update the input param of clear_upper_bits

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

Since in rv32 'G' is type of unsigned long and 32bit, '4*G' is 33bit width and out of range, so change '< 4*G' to '<= 4*G -1'.

Fix compare results about 4*G in macroAssembler_riscv32.cpp

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

In the function MacroAssembler::la_patchable, use the movptr_with_offset() function in the else branch, just comment the if
branch.

Fix the warning in the macroAssembler_riscv32.cpp

---

src/hotspot/cpu/riscv32/assembler_riscv32.cpp
src/hotspot/cpu/riscv32/assembler_riscv32.hpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp
src/hotspot/cpu/riscv32/nativeInst_riscv32.hpp
src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp
src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp
src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

The movptr_with_offset is unnecessary in 32bit, it is created to find addr which more than 4G.
Use the auipc to instead of the movptr_with_offset.
Just keep the movptr.

Remove the pseudoinstruction movptr_with_offset

---

src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp

Before this patch, the nums in li() is 64 bit version, when compiled they will info some warning.
This patch fixed them to 32 bit version.

Fix the waring in li() of sharedRuntime_riscv32.cpp

---

src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp

This will fix the SIGILL(0x4) error.

Remove the 32bit->64bit in generate_fill() in stubGenerator_riscv32.cpp

---

src/hotspot/cpu/riscv32/templateTable_riscv32.cpp
src/hotspot/share/runtime/stubRoutines.cpp

The lload(int n) accept a arg which n = 8, it is a wrong arg. Just add a condition to avoid break the
program, and will deal with it in the future.

Add a condition for lload(int)

---

src/hotspot/cpu/riscv32/assembler_riscv32.cpp

The auipc need to add 0x800 to make sure the low 12bit in the next instruction will load right, if not
the low 12 bit maybe used from unsigned to signed.

Improve the auipc in assembler

---

src/hotspot/cpu/riscv32/assembler_riscv32.hpp

Just delete some unused code and use the int32_t instead of int64_t.

Update the code of lb/lbu/lh/lhu/lw

---

src/hotspot/cpu/riscv32/assembler_riscv32.cpp
src/hotspot/cpu/riscv32/assembler_riscv32.hpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp
src/hotspot/cpu/riscv32/nativeInst_riscv32.hpp
src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp
src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp
src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

Change some auipc to lui with parameter of absolute address and add 0x800 to make sure the low 12bit in the next instruction will load right.
Change some comment text of 'auipc' to 'lui'.
Remove uesless 'if' of distance judgement and typecast of int32_t.

Fix auipc instruction added after removing movptr_with_offset

---

src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

Base the new code, the lload function don't need the condition to protect it. So remove the condition.

Remove the condition in lload

---

src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

The long/double are 64 bit, so it need to deal. This patch update the load/store of long/double in
templateTable according the arm32.

update the load/store of long/double

---

src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

The D extension widens the 32 floating-point registers to 64 bit. So the dload and dstore can keep
the same with the 64bit version. So just make them follow the bishengjdk.

update the dload and dstore

---

src/hotspot/cpu/riscv32/assembler_riscv32.hpp

The registerSize of rv32g must be 32, not be 64. So, update the value of registerSize to 32.

Update the registerSize

---

src/hotspot/cpu/riscv32/assembler_riscv32.hpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp
src/hotspot/cpu/riscv32/riscv32.ad
src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp

Remove amoswap_d, amoadd_d, amoxor_d, amoand_d, amoor_d, amomin_d, amomax_d , amominu_d, amomaxu_d in src/hotspot/cpu/riscv32/assembler_riscv32.hpp.
Remove addw, addalw, xchgw, xchgalw and fix xchg, xchgal, xchgu, xchgalu in src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp.
Remove atomic_xchgw, atomic_xchgalw, atomic_xchgwu, atomic_xchgalwu and add atomic_xchgu, atomic_xchgalu in src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp.
Change text of atomic_xchgwu to atomic_xchgu and change text of atomic_xchglwu to atomic_xchglu in src/hotspot/cpu/riscv32/riscv32.ad.
Change amoadd_d to amoadd_w in src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp.

Remove RV64A and fix RV32A instructions

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

Since the instructions sequence of 'movptr' changed from 'lui + addi + slli + addi + slli + addi/jalr/load' to 'lui + addi', function 'patch_addr_in_movptr' should be fixed.

Fix patch_addr_in_movptr

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

Since bit operation in patch_addr_in_movptr is still work with 64bit, fix it.

Fix bit operation in patch_addr_in_movptr

---

src/hotspot/cpu/riscv32/gc/shared/barrierSetAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

Change lr_d/sc_d to lr_w/sc_w in macroAssembler_riscv32.cpp and barrierSetAssembler_riscv32.cpp for riscv32.

Fix lr_w and sc_w in macroAssembler_riscv32.cpp

---

src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

Fix the offset of slli on TemplateTable::prepare_invoke from 3 to 2.

fix slli on prepare_invoke for riscv32

---

src/hotspot/cpu/riscv32/interpreterRT_riscv32.cpp

Because it is RV32, when calling C++ method from JVM, two registers are needed to pass long type parameters.

Fix parameter passing of long type when calling native method.

---

src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp

The offset in the TemplateInterpreterGenerator::generate_throw_exception() is still 64bit, need to deal.
This patch fix two slli and two 2*wordSize, they all deal the offset problem.

Fix the offset in exception

---

src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

Before this patch, the ldc can't load the right data, it will cause the bytecode go to wrong direction.
This patch changed two slli inst, it will make the ldc work correctly.

Fix the ldc bug

---

src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

The length of pointer is 4, so fix the offset of slli from 3 to 2.

fix slli on wide() and multianewarray()

---

src/hotspot/cpu/riscv32/interp_masm_riscv32.cpp
src/hotspot/cpu/riscv32/interp_masm_riscv32.hpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

Add register parms of pop_l in interp_masm_riscv32.cpp.
Change the declaration of pop_l in interp_masm_riscv32.hpp.
Change the parms of pop_l and register of the next instruction in templateTable_riscv32.cpp.
With the previous commit of pop_l fixed, add high 32-bit comparation of cmp_l2i in macroAssembler_riscv32.cpp.

Fix pop_l and lcmp

---

src/hotspot/cpu/riscv32/interp_masm_riscv32.cpp
src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp
src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp
src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp
src/hotspot/cpu/riscv32/templateTable_riscv32.cpp
src/hotspot/cpu/riscv32/vtableStubs_riscv32.cpp

The value of StackAlignmentInBytes has changed from 16 to 8. But some code still use the 16 as the bytes alignment of stack, this patch will fix the problems,change the 16 to 8.

Fix the nums of StackAlignmentInBytes

---

src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

Revert register of TemplateTable::wide_istore in templateTable_riscv32.cpp.
Fix add sub mul and or xor of TemplateTable::lop2 in templateTable_riscv32.cpp.

Fix lop2 generator

---

src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

The laload and lastore need to deal with long value, so they need to use two registers to
deal wit the long value, this patch fix them.
Need to be notice: this patch use twice access_store_at
and twice access_load_at, then the long in store_at and load_at
don't need to special deal long again.

Fix laload/lastore

---

src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

Fix that the field data failed to be zeroed when creating the object.

Fix that the field data failed to be zeroed when creating the object.

---

src/hotspot/os_cpu/linux_riscv32/copy_linux_riscv32.inline.hpp

In the pd_conjoint_oops_atomic() function, there is an assert error of BytesPerLong,
this patch will fix this error according the implementation of arm.

Fix the assert error of BytesPerLong

---

src/hotspot/cpu/riscv32/gc/shared/barrierSetAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/interp_masm_riscv32.cpp
src/hotspot/cpu/riscv32/interp_masm_riscv32.hpp
src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp
src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

Merge the rv32g-dev-pushl branch into the rv32g-dev. The  rv32g-dev-pushl branch fix the problem about pushl and some errors based the pushl. 
The  rv32g-dev-pushl branch can run the java -version on the fastdebug and slowdebug.

Rv32g dev pushl

---

src/hotspot/cpu/riscv32/assembler_riscv32.hpp
src/hotspot/cpu/riscv32/icBuffer_riscv32.cpp
src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp

Some data in RV32 is already 32bit, but their type are still int64, this patch
fix them.

Use int32 to instead some int64

---

src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

* Only the low 6 bits of rs2 are considered for the shift amount.

Fix lshl/lshr/lushr in templateTable

---

src/hotspot/cpu/riscv32/jniFastGetField_riscv32.cpp

Expand BUFFER_SIZE in jniFastGetField_riscv32.cpp, to fix exceptions in codeBuffer.cpp when the release version is running.

Expand BUFFER_SIZE in jniFastGetField_riscv32.cpp

---

src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

* The current instruction only works with single-precision 0, so modified to load double-precision 0 from memory.

Fix dconst in templateTable_riscv32.cpp

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

The patch_addr_in_movptr() give a wrong addr to the patch(), it will cause a internal error in patch(), which
is the val too big for insn.
The get_target_of_movptr() still is 64bit version, need to improve to 32bit version.

Fix the patch_addr_in_movptr and get_target_of_movptr

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

Whe use 'make' not 'make images', the 'java -version' will give us 'Field too big for insn' error in
patch(). According the error info, we need fix the data patch and get in the movptr and li.
This patch update the patch_addr_in_movptr(),patch_imm_in_li(),get_target_of_movptr()andget_target_of_li(),
the update all about the data and insn position.
After this patch, the 'make' and 'make images' will get the same result.

Fix the error of java -version when use 'make'

---

make/autoconf/build-aux/autoconf-config.guess
make/autoconf/build-aux/autoconf-config.sub
make/autoconf/build-aux/config.guess

With reference to https://bugs.openjdk.java.net/browse/JDK-8283020, there is the same issue on the riscv32 platform.
This patch will remove some modification about autoconf-* files due to legal reasons.

Fix configure integration

---

src/hotspot/os/linux/os_linux.cpp
src/hotspot/share/runtime/thread.hpp
src/hotspot/share/runtime/thread.inline.hpp

Modify the RISCV32 name system accoriding the AARCH64.
Improve the thread code in thread.hpp and thread.inline.hpp according the
http://hg.openjdk.java.net/jdk/jdk/rev/c153b4c52e39 .
After this commit, the make of slowdebug version can compiled success, but when run the
java -version, it still have the thread error. The error is same as the 'make images' of
slowdebug compiling.

Modify the RISCV32 name system and improve the thread code

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp
src/hotspot/cpu/riscv32/riscv32.ad

* Since 'is64' is always false in riscv32, remove parameter 'is64' in spillu/unspill/unspillu.
* The operations of 'unspillu' are exactly the same with 'unspill', so remove 'unspill'.
This patch has no effect on the current results.

Fix spillu/unspill/unspillu in C2

---

src/hotspot/cpu/riscv32/jniTypes_riscv32.hpp

Refer to arm32, Fix pass long args in jniTypes_riscv32.hpp

Fix pass long args in jniTypes_riscv32.hpp

---

src/hotspot/cpu/riscv32/riscv32.ad

Since is64 is always false in riscv32, remove parameter 'is64' in 'st->print'.

Fix is64 in riscv32.ad

---

src/hotspot/cpu/riscv32/riscv32.ad

This problem dealed in the d84914fc7716826795cca5ca8494ba4b196077a7, but just remove the code.
This patch will fix the problem directly through use the new long registers.
This patch study the deal method of arm32.

Fix the 'only bound registers can be killed'

---

src/hotspot/cpu/riscv32/jniTypes_riscv32.hpp

Refer to arm32, Fix pass double args in jniTypes_riscv32.hpp

Fix pass double args in jniTypes_riscv32.hpp

---

src/hotspot/cpu/riscv32/jniFastGetField_riscv32.cpp

Fix lw about long due to Long data is 8 bytes in riscv32.

Fix generate_fast_get_int_field0 on jniFastGetField_riscv32.cpp

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp
src/hotspot/cpu/riscv32/riscv32.ad

* Since the floating-point register needs to determine whether it is a 64-bit operation, revert the judgment of 'is64'.

Revert 'is64' in riscv32.ad and macroAssembler_riscv32.hpp

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

Fix insufficient codebuffer caused by align logic in MacroAssembler::emit_trampoline_stub function

Fix insufficient codebuffer caused by align logic in MacroAssembler::emit_trampoline_stub function

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

When a 32 bit data used in lui-addi, we need to devision it to two numbers, one is
20bit and the other is 12bit, we will add them into one number in the future. So
we need to make sure they will get the same nubmer compared to the original number,
this need us to add a 0X800 into 20bit number or make 'upper = tagert -lower'.
This patch dealed with the lui-addi, also according the auipc-addi code.

Fix the data of lui/addi

---

src/hotspot/cpu/riscv32/nativeInst_riscv32.hpp

* In check_movptr_data_dependency, addi is the second instruction so check the rs1 field and the rd field of addi.
* In check_li_data_dependency, lui is the second instruction so add 4 offsets to 'instr'.
* Fix typo error of addiw to addi.

Fix check data dependency of movptr and li

---

src/hotspot/cpu/riscv32/riscv32.ad

In RV32, the shamt[5] of slli must be 0.
This patch make the shamt[5] be 0 use the ox1f to & with the constant.

Fix slli shamt

---

src/hotspot/cpu/riscv32/riscv32.ad

* Remove reg_class 'all_reg' and replaced it with all_reg32/long_reg.
* Replace R0, R1, R2, R3 with R10, R11, R12, R13.
* Add reg_class 'long_reg' and put R10, R11, R12, R13 into.
* Add hi array in OptoRegPair.
* Remove useless iRegL_R10.
* Remove useless clear_upper_bits.
* Fix 'convI2L_reg_reg'.
Co-authored-by: zifeihan <caogui@iscas.ac.cn>

Fix bad AD file with 'CmpUL'

---

src/hotspot/cpu/riscv32/riscv32.ad

Long data processing requires two registers to operate simultaneously, so one (StoreL ConL) be not cheaper than two (StoreI ConI). Fix the return value be false.

Fix Matcher::isSimpleConstant64 on riscv32.ad

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp

* Register mask of '0x80000040' operates << t1 & xmethod >> here, which should be '0x80000020' for << t0 & xmethod >>.
* This PR also removes MacroAssembler::call_native_base and MacroAssembler::call_native_base, expands the definitions of call_native_base to MacroAssembler::call_VM_leaf_base directly.
Co-authored-by: Feilong Jiang <fjiang@openjdk.org>

Fix incorrect register mask in call_native_base according to JDK-8285303

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp

The fld/fsd need two wordsize in RV32G, this patch will fix the bug.
Co-authored-by: zhangxiang<zhangxiang@iscas.ac.cn>

Fix the wordsize offset of fld/fsd

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

In string_compare(), the string are different type: LL/UL/LU/UU, they are different
bytes count, so need to update them according the RV32G.

Modify the counts in string_compare()

---

src/hotspot/cpu/riscv32/icBuffer_riscv32.cpp

In RV64, the address length is 8 bytes, and since instruction_size has a value of 4, you need multiplied by. In Rv32, instead of multiplying by 2, the corresponding return value of 6 is 5, and 5 is 4..

Fix the return value on ic_stub_code_size()

---

src/hotspot/cpu/riscv32/register_riscv32.cpp
src/hotspot/cpu/riscv32/register_riscv32.hpp
src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp
src/hotspot/cpu/riscv32/vmreg_riscv32.hpp
src/hotspot/cpu/riscv32/vmreg_riscv32.inline.hpp

* In rv32 the size of the slot is 32 bits, so there is no need to shift left in register_riscv32.xxx. At the same time, max_slots_per_register, which is the number of slots in each register, also needs to be modified, 2 for 64 bits and 1 for 32 bits.
* 'max_gpr' will cause problems caused by halving the number of rv32 integer registers in ConcreteRegister, so it also needs to be adjusted.
* In 'java_calling_convention' and 'c_calling_convention', referring to the implementation of arm32 and x86_32, the minimum value of slot (stk_args) is changed to 1, and the logic of T_LONG/T_INT is modified, which has no effect on the current result.
* In 'long_move' and 'double_nove', add processing of data stored in registers and stacks respectively.
* In 'save_native_result' and …

Fix slots number in register/vmreg and processing of long in sharedRuntime

---

src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp

Since the length of the long is a 64-bit, the processing of T_LONG needs to be modified by referring to x86_32.

Fix T_LONG on SharedRuntime::gen_i2c_adapter

---

src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp

Refer to RV64 for the offset in generate_compare_long_string_different_encoding to use wordSize instead.

Fix generate_compare_long_string_different_encoding

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

The load/store_sized_value() still deal the 8 bytes, they need to fix for RV32G which is
4 bytes.
Co-authored-by: zhangxiang<zhangxiang@iscas.ac.cn>

Fix the load/store_sized_value()

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

MacroAssembler::zero_words() has a 8 bit offset, it must same with the wordsize. The
wordsize of rv32g is 4, so use the wordsize instead of the 8.

Fix offset in MacroAssembler::zero_words()

---

src/hotspot/cpu/riscv32/riscv32.ad

Since long data requires two registers to load in RISCV32, it needs to be modified in riscv32.ad.

Fix loadl instruct

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp

Co-authored-by: Ningning Shi(史宁宁) <shiningning@iscas.ac.cn>

Fix MacroAssembler::zero_words failed to clear memory completely

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

The address of a buffer to be zeroed are 8 bytes aligned. The operation of zero must
do two times, which one time zero a wordSize(4 bytes). This patch will fix this function,
it can make all the addr zeroed.

Fix the zero_words(Register, u_int32_t)

---

src/hotspot/cpu/riscv32/riscv32.ad

`negL_reg` need specially operation bacause of c2 long int register.

Fix negL_reg in riscv32.ad

---

src/hotspot/cpu/riscv32/riscv32.ad

In addI_reg_imm_l2i/convL2I_reg, only `src1.lo` is in use.

Fix addI_reg_imm_l2i/convL2I_reg in riscv32.ad

---

src/hotspot/cpu/riscv32/riscv32.ad

Refer to the RV32 interpreter. When performing ORL operations on long data, it is necessary to perform ORL operations on high-order registers and low-order registers respectively.

Fix orL_reg_reg in riscv32.ad

---

src/hotspot/cpu/riscv32/riscv32.ad

In RISCV32, long registers need to perform XORL operations on high and low registers respectively

Fix xorL_reg_reg in riscv32.ad

---

src/hotspot/cpu/riscv32/riscv32.ad

In RISCV32, XORL operations are performed on the high register and low register respectively in the long register and long immediate register.

Fix xorL_reg_imm in riscv32.ad

---

src/hotspot/cpu/riscv32/riscv32.ad

In RISCV32, the ORL operation of long register and long immediate register requires orL operation of high register and low register respectively.

Fix orL_reg_imm in riscv32.ad

---

src/hotspot/cpu/riscv32/riscv32.ad

Co-authored-by: Dingli Zhang dingli@iscas.ac.cn
High 32 bit should be zero in loadUI2l/loadI2L，and consider the sign bit in loadI2L.

Fix loadI2L/loadUI2L

---

src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp
src/hotspot/cpu/riscv32/nativeInst_riscv32.hpp

The movptr condition is not as same as the insns in movtpr(), so update it according the
rv64g.
The movprt data dependency is also need to update, it is not same with li.

Update the movptr condition and data dependency

---

src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp

The long of rv32g need to use two register, so need to add T_LONG and code for long in
save/restore_native_result.

Add T_LONG for save/restore_native_result

---

src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp

The T_DOUBLE is different with long in rv32g, it need to deal in a different way.

Update the T_DOUBLE code in sharedruntime

---

src/hotspot/cpu/riscv32/vmreg_riscv32.cpp

The int reg are 32, but the regName still set as 64, it need to delete a
regeName inst in for.

Fix the bug of regname

---

src/hotspot/cpu/riscv32/assembler_riscv32.hpp

The int reg don't have the reg like R1_H, so the next of R16 must R17. The j_rarg7 is c_rarg0,
it is the x10, but the j_rarg6 is c_rarg7 which is x17. The list can't be right in the next(),
so change the java function registers.

change the relationship between j_rargx and c_rargx

---

src/hotspot/cpu/riscv32/vtableStubs_riscv32.cpp

The 4 instructions must offset 16, not can be 8.

Fix the instructions offset in vtableStubs_riscv32.cpp

---

src/hotspot/cpu/riscv32/riscv32.ad

The long in rv32g need two regs and special deal, this patch will
fix the subL_reg_reg() in riscv32.ad.
Co-authored-by: zhangxiang<zhangxiang@iscas.ac.cn>

Fix the subL_reg_reg

---

src/hotspot/cpu/riscv32/riscv32.ad

The mulL in riscv32.ad will deal the mul of two long which in reg, but the long
in rv32g need two regs. This patch will fix the problem.
Co-authored-by: zhangxiang<zhangxiang@iscas.ac.cn>

Fix the mulL() in riscv32.ad

---

src/hotspot/cpu/riscv32/riscv32.ad

The loadConl will load a long imm, but the rv32g just can give a 32bit
data, so it need to set 0 int the high reg.

Fix the loadConL in riscv32.ad

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp
src/hotspot/cpu/riscv32/riscv32.ad
src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

The code of div system need to improve, then we need to build a new div system for rv32g.
In rv32g div system, the int data use the div/rem, the long data need to deal with more
calcute insts.
This patch will clean the code, and delete some code we will not need. This patch will not
change the result of any type div.

improve the div system

---

src/hotspot/cpu/riscv32/riscv32.ad

The storeLConditional need to compare and store two regs data, and then
need to compare the two result, they all be 0 will success.
This patch do the compare and store two times, and orr the result.

Fix the storeLConditional

---

src/hotspot/cpu/riscv32/riscv32.ad

The compareAndSwapL need to call cmpxchg() two times, so changed the riscv32_enc_cmpxchg() to riscv32_enc_cmpxchgl(),
changed the riscv32_enc_cmpxchgw() to riscv32_enc_cmpxchg().
Before this patch the riscv32_enc_cmpxchg() and riscv32_enc_cmpxchgw() are same with each other.
The riscv32_enc_cmpxchgl() will call cmpxchg() two times and will be called by the compareAndSwapL.

Fix the compareAndSwapL in riscv32.ad

---

src/hotspot/cpu/riscv32/riscv32.ad

The compareAndExchangeLAcq() is same with the compareAndExchangeL(), except
use the Assembler::aq instead of the Assembler::relaxed.
So this patch fix the compareAndExchangeLAcq() followed the compareAndExchangeL().

Fix the compareAndExchangeLAcq()

---

src/hotspot/cpu/riscv32/riscv32.ad

The weakCompareAndSwapL() need to call cmpxchg_weak twice, and their result need to use xori,
the two result of xori still need the andr to combine them.

Fix the weakCompareAndSwapL()

---

src/hotspot/cpu/riscv32/riscv32.ad

The weakCompareAndSwapLAcq is same with the weakCompareAndSwapL, except the
different of Assembler::aq.

Fix the weakCompareAndSwapLAcq

---

src/hotspot/cpu/riscv32/riscv32.ad

The get_and_setI just call the atomic_xchg directly.
The get_and_setL need to call the atomic_xchg two times.

Fix the get_and_setI/F

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/riscv32.ad

Some xchg funcs are not need in rv32g, delete them to improve the code quality.

Improve the xchg system

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/riscv32.ad

Some funcs of atomic_add system are not need in rv32g, remove them and
make the code more clearly.

Improve the atomic_add system

---

src/hotspot/cpu/riscv32/riscv32.ad

The lShiftL_regI_immGE32 instruct is no need in rv32g, so remove it.

Remove the lShiftL_regI_immGE32

---

src/hotspot/cpu/riscv32/riscv32.ad

The comment of subI_reg_imm give a wrong direction, so just remove it.

Remove the comment of subI_reg_imm

---

src/hotspot/cpu/riscv32/riscv32.ad

The mulHiL_rReg need to mul two long data, and save the high 32-bit data into dst.
The mulHiL_rReg code is according the mulL.

Fix the mulHiL_rReg

---

src/hotspot/cpu/riscv32/riscv32.ad

signExtractL need to srli 63, so just need the high 32bit srli 31, then save the result
into the dst.

Fix the signExtractL

---

src/hotspot/cpu/riscv32/riscv32.ad

The urShiftP_reg_imm in rv32g just need to srli 5bit.

Fix the urShiftP_reg_imm

---

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp
src/hotspot/cpu/riscv32/riscv32.ad

The urShiftL_reg_reg/imm need to srl a long data from 0 to 64. This need to do more operation in rv32g.

Fix the urShiftL_reg_reg/imm

---

src/hotspot/cpu/riscv32/riscv32.ad

The long data in rv32g need two regs, so the two regs all need to do the xori.

Fix the regL_not_reg

---

src/hotspot/cpu/riscv32/interp_masm_riscv32.cpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp
src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

The grevw system of rv64 are too complex for rv32g, some functions can be deleted.
This patch refactor the grevw system to fit the rv32g.

Refactor the grevw system

---

src/hotspot/cpu/riscv32/riscv32.ad

The long data need two regs in rv32g, the high reg must be 0.

Fix the convUI2L_reg_reg

---

src/hotspot/cpu/riscv32/riscv32.ad

The get_and_setL/addL need atomic opeartion in rv64, but it can't be deal in rv32. We can call the std::atomic_fetch_add to fix this, but it is not suit for the C2. So just remove the instructs, let the interpreter to deal them.

Remove the get_and_setL/addL

---

src/hotspot/cpu/riscv32/riscv32.ad

The riscv32.ad call the cmp_branch when the compare input is long, this need to fix. This patch will use the call of long_cmp_branch to instead of the cmp_branch.

Use the long_cmp_branch to instead of the cmp_branch

---

src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp

The java_calling_convention in sharedRuntime_riscv32.cpp need to update, after this patch it will more same with rv64g.
This patch will not change the result.

Update the java_calling_convention

---

src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp

Update the c_calling_convention in sharedRuntime_riscv32.cpp, this patch will make the code more easy to understand and more same with the rv64g.

Update the c_calling_convention

---

src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp

Fix the int_args and stk_args in the java_calling_convention and c_calling_convention. They are align 2 in these functions.

Fix the int_args and stk_args in x_calling_convention

---

src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp

The save_native_result must use the sw, not the lw. This patch will fix that.

Fix the insns errors in save_native_result

---

src/hotspot/cpu/riscv32/riscv32.ad

The cmovI_cmpL need to compare the long data, so it need to use the long_cmp_branch. This patch will fix that.

Fix the cmovI_cmpL

---

src/hotspot/cpu/riscv32/riscv32.ad

Use the cmpxchg_long to instead of the twice cmpxchg.

Improve the compareAndSwapL/compareAndSwapLAcq

---

src/hotspot/cpu/riscv32/riscv32.ad

The RFLAGS sometimes need to store the long data, so it need to use the x5. Some RFLAGS be instead of t1, they are not incorrect.

Fix the RFLAGS in riscv32.ad

---

src/hotspot/cpu/riscv32/riscv32.ad

The RegisterImpl::number_of_registers don't need to - 2, because it will not change in riscv32.ad, it is always 32.

Fix the RegisterImpl::number_of_registers in riscv32.ad

---

src/hotspot/cpu/riscv32/assembler_riscv32.hpp

The 'java function register(caller-save registers)' has changed in the PR472, but this change will make the TestReflectInvoke testcase of interpreter failed. This pr will fix that. After this change, the TestReflectInvoke testcase of interpreter will successed.

Changed the 'java function register(caller-save registers)'

---

src/hotspot/cpu/riscv32/riscv32.ad

If the dst is same with the mem, it need to store the hi 32bit data. It can avoid the data been rewrite.

Fix the loadL according the arm 32bit
