src/hotspot/cpu/riscv32/vmStructs_riscv32.hpp, src/hotspot/cpu/riscv32/vm_version_ext_riscv32.cpp, src/hotspot/cpu/riscv32/vm_version_ext_riscv32.hpp, src/hotspot/cpu/riscv32/vm_version_riscv32.cpp, src/hotspot/cpu/riscv32/vm_version_riscv32.hpp, src/hotspot/cpu/riscv32/vmreg_riscv32.cpp, src/hotspot/cpu/riscv32/vmreg_riscv32.hpp, src/hotspot/cpu/riscv32/vmreg_riscv32.inline.hpp
Add the vm files, it is same with the files of the BishengJDK for riscv64, except changed the file name and some '64' text.
=> Add vm files into src/hotspot/cpu/riscv32

src/hotspot/cpu/riscv32/registerMap_riscv32.hpp, src/hotspot/cpu/riscv32/register_definitions_riscv32.cpp, src/hotspot/cpu/riscv32/register_riscv32.cpp, src/hotspot/cpu/riscv32/register_riscv32.hpp
Add the register related files, they are same with the files of the BishengJDK for riscv64, except changed the file name and some '64' text.
=> Add register related files into src/hotspot/cpu/riscv32

src/hotspot/cpu/riscv32/frame_riscv32.cpp, src/hotspot/cpu/riscv32/frame_riscv32.hpp, src/hotspot/cpu/riscv32/frame_riscv32.inline.hpp, src/hotspot/cpu/riscv32/javaFrameAnchor_riscv32.hpp
Add the frame_riscv32.cpp, frame_riscv32.hpp, frame_riscv32.inline.hpp, javaFrameAnchor_riscv32.hpp into the src/hotspot/cpu/riscv32 dir. These files are same with the riscv64 version files of the BishengJDK but change the '64' to '32' in the files and files' name.
=> Add the frame files into src/hotspot/cpu/riscv32

src/hotspot/cpu/riscv32/jniFastGetField_riscv32.cpp, src/hotspot/cpu/riscv32/jniTypes_riscv32.hpp
Add the jniFastGetField_riscv32.cpp, it is same with the jniFastGetField_riscv64.cpp of BishengJDK, except changed the ld->flw.
Add the jniTypes_riscv32.hpp, it is same with the jniTypes_riscv64 of BishengJDK, except changed the text '64' to '32'.
=> Add the jni files into src/hotspot/cpu/riscv32

src/hotspot/cpu/riscv32/icache_riscv32.cpp, src/hotspot/cpu/riscv32/icache_riscv32.hpp
Add the icache files, they are same with the files of the BishengJDK for riscv64, except changed the file name and some '64' text.
=> Add icache files into src/hotspot/cpu/riscv32

src/utils/hsdis/README, src/utils/hsdis/hsdis.c
Update the README and hsdis.c according the BishengJDK, just changed
the riscv64 text to riscv32.
=> Update the hsdis according the BishengJDK

src/hotspot/cpu/riscv32/riscv32-asmtest.py
Add the riscv32-asmtest.py, compared with the riscv64-asmtest.py of BishengJDK, it has changed: 1)remove the following instructions:addw,subw,mulw,divw,divuw,remw,remuw,addiw,sraw,sllw,srlw,slliw,srliw,sraiw,sc.d,amoswap.d,amoadd.d,amoxor.d,amoand.d,amoor.d,amomin.d,amomax.d,amominu.d,amomaxu.d,lr.d,negw,sext_w,ld,lwu,sd,fmv.x.d,fcvt.l.s,fcvt.lu.s,fcvt.s.l,fcvt.s.lu,fcvt.l.d,fcvt.lu.d,fcvt.d.l,fcvt.d.lu; 2)changed the 64 text to 32.
=> Add riscv32-asmtest.py file into src/hotspot/cpu/riscv32

src/hotspot/cpu/riscv32/icBuffer_riscv32.cpp, src/hotspot/cpu/riscv32/interp_masm_riscv32.cpp, src/hotspot/cpu/riscv32/interp_masm_riscv32.hpp, src/hotspot/cpu/riscv32/interpreterRT_riscv32.cpp, src/hotspot/cpu/riscv32/jniFastGetField_riscv32.cpp, src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp, src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp, src/hotspot/cpu/riscv32/templateTable_riscv32.cpp
This update some flw->lw, fsw->sw.
Before this update, some ld transalted to flw, sd translated to fsw. After this update, the ld->lw, sd->sw.
=> update the flw and fsw instructions

src/hotspot/cpu/riscv32/globals_riscv32.hpp, src/hotspot/cpu/riscv32/methodHandles_riscv32.cpp, src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp, src/hotspot/cpu/riscv32/vtableStubs_riscv32.cpp
This update some flw->lw, fsw->sw.
Before this update, some ld transalted to flw, sd translated to fsw. After this update, the ld->lw, sd->sw.
=> update the flw and fsw instructions in methodHandle and stub

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
The warnings are caused by the offset of 64bit, translate them to 32bit will fix the warnings.
=> Fix the warnings in macroAssembler_riscv32.cpp

src/hotspot/cpu/riscv32/riscv32.ad
Add the riscv32.ad, it is same with the riscv64.ad of BishengJDK except changed the text '64' to '32'.
More changes will be added after starting C1 porting.
=> Add riscv32.ad into src/hotspot/cpu/riscv32

src/hotspot/share/gc/shenandoah/shenandoahArguments.cpp, src/hotspot/share/jfr/utilities/jfrBigEndian.hpp, src/hotspot/share/runtime/thread.hpp, src/hotspot/share/runtime/thread.inline.hpp, src/hotspot/share/utilities/globalDefinitions_gcc.hpp
Add the RISCV32 setting in the src/hotspot/share, the locations are same with the RISCV64 in BishengJDK.
=> Update the RISCV32 setting in src/hotspot/share

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp, src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp, src/hotspot/cpu/riscv32/nativeInst_riscv32.hpp
Remove all the li64 and li32, use the li instead of them.
Also update some code and comments in the related code about li.
=> Clean the functions about li

src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp, src/hotspot/share/runtime/stubRoutines.cpp
Improve the code of generate_fill(), but not fix the error of TESTFILL, still need more work.
Remove the TESTFILL tests, still need to let them work in future.
=> Improve the code of generate_fill()

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp, src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp, src/hotspot/share/runtime/stubRoutines.cpp
Fix the generate_fill and make the TEST_FILL work.
Make the StubGenerator_generate() function work again, it is not the main reason of IIGSEGV error.
=> Fix the generate_fill

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
=> remove some redundancy code

src/hotspot/cpu/riscv32/icBuffer_riscv32.cpp, src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp, src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp, src/hotspot/cpu/riscv32/nativeInst_riscv32.hpp, src/hotspot/cpu/riscv32/riscv32.ad, src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp
Use the lw to instead ld and lwu, use the sw to instead sd.
Clean the ld/lwu/sd in comments.
=> Clean the ld/lwu/sd

src/hotspot/cpu/riscv32/interp_masm_riscv32.cpp, src/hotspot/cpu/riscv32/templateTable_riscv32.cpp
The long data need to deal with different ways in 32bit, so just fix the error according the arm32.
=> Fix some error about long

src/hotspot/cpu/riscv32/interpreterRT_riscv32.cpp
Fix that the registers are not enough to pass Long parameters using the stack to pass parameters.
=> Fix that the registers are not enough to pass Long parameters using the stack to pass parameters

src/hotspot/cpu/riscv32/templateTable_riscv32.cpp
Fixing the lshl becuse the sizeof long is 8
=> fix lshl in rv32

src/hotspot/cpu/riscv32/assembler_riscv32.hpp, src/hotspot/cpu/riscv32/icBuffer_riscv32.cpp, src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp, src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp, src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp, src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp, src/hotspot/cpu/riscv32/templateTable_riscv32.cpp
Fix the javac problems of debug model.
=> Rv32g dev javac

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp, src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp, src/hotspot/cpu/riscv32/templateTable_riscv32.cpp
* Use SharedRuntime to implement convert of long/double/float.
=> Fix convert of long/double/float

src/hotspot/os_cpu/linux_riscv32/atomic_linux_riscv32.hpp, src/hotspot/share/runtime/atomic.hpp
Fix pr170 on platform store and platform load due to fixing public code on atomic.hpp ago.
=> Fix pr170 on PlatformLoad and PlatformStore

src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp
Co-authored-by: zhangxiang-plct <zhangxiang@nj.iscas.ac.cn>
=> Fix the slli instruction, and the offset when the sp register is moved.

src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp
Use the wordSize intead of the magic number 8.
=> Imporve the COMPILER2 code in stubGenerator_riscv32.cpp

src/hotspot/cpu/riscv32/riscv32.ad
Delete  code about 64-bit registers on riscv32.ad.
=> Delete  code about 64-bit registers on riscv32.ad

src/hotspot/cpu/riscv32/riscv32.ad
Co-authored-by: Dingli Zhang <dingli@iscas.ac.cn>
=> Fix bad AD file with 'OrI'

src/hotspot/cpu/riscv32/globals_riscv32.hpp, src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
Update the string_compare()\inflate_lo32()\infalte_hi32() according the bishengjdk code.
=> update the bishengjdk to improve string compare funcs

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
The string_indexof() still has some RV64 code, so need to improve them.
This patch improved the string_indexof() function. After this patch, the
code is same with the comment.
=> modify the string_indexof()

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
Update a comment in grevwu().
Update the func string_equal() according the newest RV64G code. And also update
the comment.
=> Improve the macroAssembler_riscv32.cpp

src/hotspot/cpu/riscv32/riscv32.ad
Refer to the interpreter in RISCV32 to modify the long register addition operation
=> Fix addL_reg_reg in riscv32.ad

src/hotspot/cpu/riscv32/riscv32.ad
High 32 bit should be zero in loadB2L and loadUB2L.
=> Fix loadB2L/loadUB2L in riscv32.ad

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
Reverts openjdk-riscv/jdk11u#441
=> Revert "Fix the zero_words(Register, u_int32_t)"

src/hotspot/cpu/riscv32/riscv32.ad
High 32 bit should be zero in loadS2L/loadUS2L，and consider the sign bit in loadS2L.
=> Fix loadS2L/loadUS2L

src/hotspot/cpu/riscv32/riscv32.ad
StoreL need specially operation bacause of c2 long int register.
=> Fix storeL

src/hotspot/cpu/riscv32/register_riscv32.cpp, src/hotspot/cpu/riscv32/register_riscv32.hpp, src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp, src/hotspot/cpu/riscv32/vmreg_riscv32.hpp, src/hotspot/cpu/riscv32/vmreg_riscv32.inline.hpp
Reverts openjdk-riscv/jdk11u#421
=> Revert "Fix slots number in register/vmreg and processing of long in sharedRuntime"

src/hotspot/cpu/riscv32/register_riscv32.cpp, src/hotspot/cpu/riscv32/register_riscv32.hpp, src/hotspot/cpu/riscv32/vmreg_riscv32.hpp, src/hotspot/cpu/riscv32/vmreg_riscv32.inline.hpp
This is the part code  in PR421, which create by dingli.
=> Fix some reg num problems

src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp
Fix the java/c-calling-convention according the PR421, arm32 arch.
=> Fix the java/c-calling-convention

src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp
The long data need two regs in rv32g, so the long_move() need to rewrite.
=> rewrite the long_move()

src/hotspot/cpu/riscv32/riscv32.ad
Fix the comments of storeL and storeimmL0.
Fix the high reg data of storeimmL0.
=> Fix the storeL and storeimmL0

src/hotspot/cpu/riscv32/riscv32.ad
Fix loadConD0 high reg in riscv32.ad.
=> Fix loadConD0 in riscv32.ad

src/hotspot/cpu/riscv32/riscv32.ad
Fix the compareAndSwapLAcq(), it is the samke like the compareAndSwapL(). Just a
different parameter.
=> Fix the compareAndSwapLAcq()

src/hotspot/cpu/riscv32/riscv32.ad
The long data need call compxchg() twice.
=> Fix the compareAndExchangeL

src/hotspot/cpu/riscv32/riscv32.ad
=> Fix the ins cost of compareAndExchangeLAcq

src/hotspot/cpu/riscv32/riscv32.ad
The shift left logic of long, need to deal two regs.
The data in two regs need to deal with different ways, if the shift left num is >= 32
or not.
=> Fix the lShiftL_reg_reg

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp, src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp, src/hotspot/cpu/riscv32/riscv32.ad
Move the implement of lShiftL_reg_reg to macroassembler.
Fix the lShiftL_reg_imm, make it call the lShiftL_reg_reg in macroassembler.
=> Rewrite the lShiftL_reg_reg and fix the lShiftL_reg_imm

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp, src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp, src/hotspot/cpu/riscv32/riscv32.ad
Fix the rShiftL_reg_reg/imm, make the long data can sra 0~64 in rv32g.
=> Fix the rShiftL_reg_reg/imm

src/hotspot/cpu/riscv32/riscv32.ad
Fix the ins_cost and format of cmpL3_reg_reg.
=> Fix the cmpL3_reg_reg

src/hotspot/cpu/riscv32/riscv32.ad
This error will not happen after we clean the build files and rebuild.
=> Remove the error comment

src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp
The long and dobule in gen_c2i_adapter/gen_i2c_adapter need to fix, after this patch, the error of offset in unfase.cpp can be fixed.
=> Fix the offset error in unsafe.cpp

src/hotspot/cpu/riscv32/riscv32.ad
The loadB2L need to sign-extend.
The loadUB2L use the mv is better to the addi.
=> Fix the loadB2L/loadUB2L

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp, src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp, src/hotspot/cpu/riscv32/riscv32.ad
The compare long is different with two compare of int.
=> Fix the storeLConditional

src/hotspot/cpu/riscv32/riscv32.ad
Use the cmpxchg_long in compareAndExchangeL/compareAndExchangeLAcq.
=> Fix the compareAndExchangeL/compareAndExchangeLAcq

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp, src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp, src/hotspot/cpu/riscv32/riscv32.ad
Add the cmpxchg_long_weak() for weakCompareAndSwapL/weakCompareAndSwapLAcq, make the result more accurate.
=> Fix the weakCompareAndSwapL/weakCompareAndSwapLAcq

src/hotspot/cpu/riscv32/riscv32.ad
Reverts openjdk-riscv/jdk11u#566
=> Revert "Use the esp operations intead of the call_VM_leaf in riscv32.ad"
